// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Iie8DY6mKhFj1AVLB0Y8AaIYsBQNBow',
    appId: '1:714519236669:web:80b5ab554b5749c35d9a54',
    messagingSenderId: '714519236669',
    projectId: 'rent-website-c1750',
    authDomain: 'rent-website-c1750.firebaseapp.com',
    storageBucket: 'rent-website-c1750.appspot.com',
    measurementId: 'G-NKGM2W8SP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC06fv9xicK-XNH1Hbig5Hg7eaROI22lJw',
    appId: '1:714519236669:android:e8bc186a1964436f5d9a54',
    messagingSenderId: '714519236669',
    projectId: 'rent-website-c1750',
    storageBucket: 'rent-website-c1750.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSDeUQYMmac-4QVEcTkePkOIXbWWSYWo',
    appId: '1:714519236669:ios:cef058cf87ae7e735d9a54',
    messagingSenderId: '714519236669',
    projectId: 'rent-website-c1750',
    storageBucket: 'rent-website-c1750.appspot.com',
    iosBundleId: 'dev.hady.rentWebsite',
  );
}
